### ISSUE TITLE
moodle import the field "coms_participant_info" is not filled

### ISSUE THREAD

**Issue by Kuhlig** [BPMspaceUG/COMS#57]
Example 

UPDATE `coms_participant_exam_event` SET `coms_participant_info`=concat("SUMM POINTS: AAA - MAX POINTS: BBB- PASS MARK: CCC% RESULT: DDD% - CHECK: EEE") where `coms_participant_exam_event`.`coms_exam_event_id` ="XXXXX" AND `coms_participant_exam_event`.`coms_participant_id`="YYYYYY";

AAA = TRUNCATE(moodle.mdl_offlinequiz_results.sumgrades,3)
BBB = bpmspace_coms_v1.coms_exam.coms_exam_max_points
CCC = bpmspace_coms_v1.coms_exam.coms_exam_pass_mark
DDD = TRUNCATE((moodle.mdl_offlinequiz_results.sumgrades/bpmspace_coms_v1.coms_exam.coms_exam_max_points*100),3)
EEE = concat("MDL",bpmspace_coms_v1.coms_exam_event.coms_exam_event_id,moodle.mdl_user.idnumber)

**Comment by Kuhlig** [comment]
RESULT: DDD% sollte am Angang stehen 
Beispiel

'RESULT: 98% -  SUMM POINTS: 49.000 - MAX POINTS: 50 - PASS MARK: 33 - CHECK: MDL876223523483'

**Comment by dwu300** [comment]
Not found in the Scripts... Needs discussion

**Comment by Kuhlig** [comment]
??? did you write that aft our telko?

**Comment by dwu300** [comment]
Now clarified with @Idefixus. Should be in Table **Exam Event** in state-transition from **upheld** -> **billable**

**Comment by dwu300** [comment]
- Tested on Test-System - Works for failed as well as succeeded
- Function is now also implemented in the Live-System
Example:
> RESULT: 73.33% - SUMM POINTS: 22 - MAX POINTS: 30 - PASS MARK 20 - CHECK: MDLXXXXXXXXXXXXXXX
