### ISSUE TITLE
Testissue for Asana

### ISSUE THREAD

**Issue by Idefixus** [BPMspaceUG/COMS#6]
Hi this is a testissue for asana

**Comment by TobiasKB** [comment]
It worked pretty damn well.

Gesendet von Mail für Windows 10

Von: Robin
Gesendet: Mittwoch, 22. November 2017 13:32
An: BPMspaceUG/COMS
Cc: Subscribed
Betreff: [BPMspaceUG/COMS] Testissue for Asana (#6)

Hi this is a testissue for asana
